version: '3'
services:
  db:
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE='social_media_api'
      - MYSQL_USER='root'
      - MYSQL_HOST='localhost'
    volumes:
      - /tmp/app/mysqld:/var/run/mysqld
      - ./db:/var/lib/mysql
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/socialMediaAPI
      - /tmp/app/mysqld:/run/mysqld
    depends_on:
      - db
